[package]
name = "stufftail"
version = "0.1.0"
edition = "2018"

[dependencies]
logstuff = { path = "../logstuff" }
serde_json = "1.0"
postgres = { version = "0.19", features = ["with-chrono-0_4", "with-serde_json-1"] }
simple-logging = "2"
log = "0.4"
clap = "2"

