# vim: set ft=yaml ts=2 sw=2 et :
# Example config file for "stuffimport"

# rsyslog forbids changing the property "msg" of an event. To allow rewriting
# of log events, stuffimport may use a json attribute (rsyslog: $!msg, logstuff
# query: vars.msg) instead of an event's msg. If enabled and an events contains
# vars.msg, msg becomes vars.msg and vice versa.
use_vars_msg: true

# TLS settings for connecting to postgres
tls:
  # Load client certificate from given PKCS#12 store (default none)
  # client_cert_store: /path/to/store.pkcs12
  # client_cert_password: secret passphrase for PKCS#12 store

  # Add trusted root certificates (default empty)
  ca_certs:
    - /etc/ssl/certs/postgres-snakeoil.pem

  # Disable trusting system's installed CA certificates (default false)
  disable_system_trust: false

# Database URL, (see
# https://docs.rs/postgres/0.19.2/postgres/config/struct.Config.html)
db_url: >-
  user=stuffimport
  password=stuffimport-password
  host=127.0.0.1
  port=5432
  dbname=log
  target_session_attrs=read-write

# LRU cache for prepared INSERT statements (default 3).
# stuffimport will use exactly one statement per root table name, so you will
# usually need only one.
statement_cache_size: 3

# Log table partitioning ordered from root to leaf (meaning: each entry defines
# partitions of the previous entry). Possible kinds so far:
# * root: Single table. This is the only valid option for the first entry and
#     only valid as first entry.
#   root Parmeters:
#     table:  Name of this table
#     schema: SQL data types in this table. Has to be compatible with
#       stuffinsert's insert statements: insert into <table name> (tstamp, doc,
#       search) values (timestamp with time zone, json, to_tsvector(text))
#
# * timerange: Partitions by event's timestamp.
#   timerange Parameters:
#     name_template: strftime format argument to get a table's name (see
#       https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html). Each
#       partition's name has to be a unique and valid postgresql table name.
#     interval: Time range of a single partition. Valid values: Year, Quarter,
#       Month, Week, Day, Hour, Minute.
partitions:
  - kind: root
    table: logs
    schema: >-
      (
        id integer not null default nextval('logs_id'),
        tstamp timestamp with time zone not null,
        doc jsonb not null,
        search tsvector
      )
  - kind: timerange
    name_template: logs_[year]_[month]
    interval: Month
