# vim: set ft=yaml ts=2 sw=2 et :
name: Rust

"on":
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        uses: actions-rs/tarpaulin@v0.1

